language: objective-c
osx_image: xcode8
branches:
  only:
    - dev
script:
- if [ $MODE == 'Tests' ]; then set -o pipefail && xcodebuild -workspace expocity.xcworkspace -scheme expocity -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" test | xcpretty -c; fi
- if [ $MODE == 'Build' ]; then xctool -workspace expocity.xcworkspace -scheme expocity -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" build; fi
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - MODE=Tests
  - MODE=Build
