language: objective-c
osx_image: xcode8
branches:
  only:
    - dev
script:
- if [ $MODE == 'Tests' ]; then set -o pipefail && xcodebuild -workspace expocity.xcworkspace -scheme expocity test | xcpretty; fi
- if [ $MODE == 'Build' ]; then set -o pipefail && xcodebuild -workspace expocity.xcworkspace -scheme expocity build | xcpretty; fi
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - MODE=Tests
  - MODE=Build
